---
AllCops:
  Exclude:
  - bin/**/*
  - vendor/**/*
  - dev/**/*
  SuggestExtensions: false
Layout/LineLength:
  Enabled: false
Layout/HashAlignment:
  Enabled: false
Layout/EmptyLineAfterMagicComment:
  Enabled: false
Layout/EndOfLine:
  Enabled: true
  EnforcedStyle: lf
Layout/ExtraSpacing:
  Enabled: true
  Exclude:
  - Gemfile
Layout/EmptyLineAfterGuardClause:
  Enabled: false
Layout/SpaceAroundOperators:
  Enabled: false
Layout/ParameterAlignment:
  Enabled: true
Layout/EmptyLinesAroundBlockBody:
  Enabled: false
Lint/MissingSuper:
  Enabled: false
Metrics/MethodLength:
  Max: 60
Metrics/AbcSize:
  Max: 75
Metrics/BlockLength:
  Max: 50
Metrics/ClassLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Max: 25
Metrics/PerceivedComplexity:
  Max: 25
Naming/FileName:
  Enabled: false
Naming/PredicateName:
  Enabled: false
Security/YAMLLoad:
  Enabled: false
Style/NumericLiterals:
  MinDigits: 10
Style/BlockDelimiters:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/AndOr:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/ConditionalAssignment:
  Enabled: false
Style/DoubleNegation:
  Enabled: false
Style/EmptyMethod:
  Enabled: false
Style/Encoding:
  Enabled: false
Style/GuardClause:
  Enabled: false
Style/IfUnlessModifier:
  Enabled: false
Style/MissingRespondToMissing:
  Enabled: false
Style/MultilineIfModifier:
  Enabled: false
Style/NegatedIf:
  Enabled: false
Style/Not:
  Enabled: false
Style/NumericLiteralPrefix:
  Enabled: false
Style/NumericPredicate:
  Enabled: false
Style/HashTransformKeys:
  Enabled: false
Style/SlicingWithRange:
  Enabled: false
Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%':  '{}'
    '%i': ()
    '%q': '{}'
    '%Q': ()
    '%r': '{}'
    '%s': ()
    '%w': '{}'
    '%W': ()
    '%x': ()
Style/SymbolArray:
  Enabled: false
Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
Style/UnlessElse:
  Enabled: false
Style/ClassVars:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/HashSyntax:
  Enabled: true
