language: ruby
branches:
  only:
  - master
rvm:
  - 2.3
  - 2.4.4
  - 2.5
  - 2.6
before_install:
  - gem update --remote bundler
install:
  - bundle install --retry=3
script:
  - bundle exec rake test:unit
  - bundle exec rake lint
