# Documentation available at https://expeditor.chef.io/docs/getting-started/
---
project:
  alias: inspec-azure

slack:
 notify_channel: inspec-notify

pipelines:
 - verify:
    description: Pull Request validation tests

github:
 delete_branch_on_merge: true
 minor_bump_labels:
  - "Version: Bump Minor"
 version_tag_format: v{{version}}

release_branches:
  - main

changelog:
 categories:
  - "Type: New Resource": "New Resources"
  - "Type: New Feature": "New Features"
  - "Type: Enhancement": "Enhancements"
  - "Type: Bug": "Bug Fixes"

subscriptions:
  - workload: pull_request_merged:{{github_repo}}:{{release_branch}}:*
    actions:
      - built_in:bump_version:
         ignore_labels:
           - "Version: Skip Bump"
           - "Expeditor: Skip All"
      - bash:.expeditor/update_version.sh:
         only_if: built_in:bump_version
      - built_in:update_changelog:
         ignore_labels:
          - "Changelog: Skip Update"
          - "Expeditor: Skip All"
  # These actions are taken when `/expeditor promote` is run from Slack
  # Creates a release by announcing changes since the last announcement
  # THE SLACK COMMAND IS `expeditor promote inspec-azure`
  - workload: project_promoted:{{agent_id}}:*
    actions:
    - bash:.expeditor/publish-release-notes.sh:
        post_commit: true
    - bash:.expeditor/announce-release.sh:
        post_commit: true
